### ISSUE TITLE
Lacks debt Control if the debt is already paid

### ISSUE THREAD

**Issue by baccalla** [waryjack/fiveparsecs#1]
Hello,
Minor Issue : If you pay credits over you debt, the debt become negative
It would be nicer having a control for preventing that
![image](https://user-images.githubusercontent.com/13984708/148696573-77dc27ba-8804-4bba-9275-03853c5aa85c.png)

Best regards

**Comment by waryjack** [comment]
This project is no longer being maintained.

**Comment by waryjack** [comment]
Hey, although I said I wasn't working on it I had a moment to look and
quickly fix it (and the other issue with item deletion not working). Here's
the link to the update (you might have to reinstall the system entirely;
not sure how that works).

https://github.com/waryjack/fiveparsecs/releases/download/0.1.6/system.json
